### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by Kensuke-Mitsuzawa** [ikegami-yukino/zunda-python#1]
# エラー内容

パッケージをimportしようとすると，エラーが出る

# 原因

記述ミス？ コンマがピリオドになっている．

# 環境

- Python3.7(conda)
- Alpine Linux

# エラーログ

```
In [1]: import zunda                                                                                                                                                          
Traceback (most recent call last):

  File "/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-eb85184370b9>", line 1, in <module>
    import zunda

  File "/opt/conda/lib/python3.7/site-packages/zunda/__init__.py", line 3
    VERSION = (0, 1. 2)
                     ^
SyntaxError: invalid syntax
```

**Comment by ikegami-yukino** [comment]
@Kensuke-Mitsuzawa 
ありがとうございます。
いただいたpull requestを反映し0.1.3にバージョンアップしてPyPIにアップロード致しました。
